# Generated by Django 5.1.6 on 2025-02-11 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.'), django.core.validators.RegexValidator('.*[A-Z].*', message='Password must contain at least one uppercase letter.'), django.core.validators.RegexValidator('.*[a-z].*', message='Password must contain at least one lowercase letter.'), django.core.validators.RegexValidator('.*\\d.*', message='Password must contain at least one number.'), django.core.validators.RegexValidator('.*[!@#$%^&*(),.?\\":{}|<>].*', message='Password must contain at least one special character.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
