# Generated by Django 5.1.6 on 2025-02-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_reset_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
