# Generated by Django 5.1.6 on 2025-02-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
