# Generated by Django 5.1.6 on 2025-02-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedPasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(unique=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
