# Generated by Django 5.1.6 on 2025-02-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usedpasswordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_change_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Email Change Verification Code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_change_code_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email Change Code Sent At'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Pending New Email'),
        ),
    ]
